import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      /* ── Font ── */
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
      },

      /* ── Typography scale (Inter Variable, rem-based) ── */
      fontSize: {
        '2xs': ['10px', { lineHeight: '14px', letterSpacing: '0.02em' }],
        'xs':  ['11px', { lineHeight: '15px', letterSpacing: '0.01em' }],
        'sm':  ['12px', { lineHeight: '16px' }],
        'base':['13px', { lineHeight: '18px' }],
        'md':  ['14px', { lineHeight: '20px' }],
        'lg':  ['15px', { lineHeight: '22px' }],
        'xl':  ['16px', { lineHeight: '24px' }],
        '2xl': ['18px', { lineHeight: '26px', letterSpacing: '-0.01em' }],
        '3xl': ['22px', { lineHeight: '30px', letterSpacing: '-0.015em' }],
        '4xl': ['26px', { lineHeight: '34px', letterSpacing: '-0.02em' }],
      },

      /* ── Colors (shadcn + Xedu tokens) ── */
      colors: {
        border:      'hsl(var(--border))',
        input:       'hsl(var(--input))',
        ring:        'hsl(var(--ring))',
        background:  'hsl(var(--background))',
        foreground:  'hsl(var(--foreground))',
        primary: {
          DEFAULT:    'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT:    'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT:    'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT:    'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT:    'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT:    'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT:    'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        /* Xedu brand system */
        'xedu-primary': {
          DEFAULT: 'var(--xedu-primary)',
          hover:   'var(--xedu-primary-hover)',
          active:  'var(--xedu-primary-active)',
          light:   'var(--xedu-primary-light)',
          muted:   'var(--xedu-primary-muted)',
        },
        'xedu-slate': {
          50:  'var(--xedu-slate-50)',
          100: 'var(--xedu-slate-100)',
          200: 'var(--xedu-slate-200)',
          300: 'var(--xedu-slate-300)',
          400: 'var(--xedu-slate-400)',
          500: 'var(--xedu-slate-500)',
          600: 'var(--xedu-slate-600)',
          700: 'var(--xedu-slate-700)',
          800: 'var(--xedu-slate-800)',
          900: 'var(--xedu-slate-900)',
          950: 'var(--xedu-slate-950)',
        },
        'xedu-ruby': {
          DEFAULT: 'var(--xedu-ruby)',
          50:  'var(--xedu-ruby-50)',
          100: 'var(--xedu-ruby-100)',
          200: 'var(--xedu-ruby-200)',
          300: 'var(--xedu-ruby-300)',
          400: 'var(--xedu-ruby-400)',
          500: 'var(--xedu-ruby-500)',
          600: 'var(--xedu-ruby-600)',
          700: 'var(--xedu-ruby-700)',
          800: 'var(--xedu-ruby-800)',
          900: 'var(--xedu-ruby-900)',
          950: 'var(--xedu-ruby-950)',
        },
        'xedu-amber': {
          DEFAULT: 'var(--xedu-amber)',
          50:  'var(--xedu-amber-50)',
          100: 'var(--xedu-amber-100)',
          200: 'var(--xedu-amber-200)',
          300: 'var(--xedu-amber-300)',
          400: 'var(--xedu-amber-400)',
          500: 'var(--xedu-amber-500)',
          600: 'var(--xedu-amber-600)',
          700: 'var(--xedu-amber-700)',
          800: 'var(--xedu-amber-800)',
          900: 'var(--xedu-amber-900)',
          950: 'var(--xedu-amber-950)',
        },
        'xedu-emerald': {
          DEFAULT: 'var(--xedu-emerald)',
          50:  'var(--xedu-emerald-50)',
          100: 'var(--xedu-emerald-100)',
          200: 'var(--xedu-emerald-200)',
          300: 'var(--xedu-emerald-300)',
          400: 'var(--xedu-emerald-400)',
          500: 'var(--xedu-emerald-500)',
          600: 'var(--xedu-emerald-600)',
          700: 'var(--xedu-emerald-700)',
          800: 'var(--xedu-emerald-800)',
          900: 'var(--xedu-emerald-900)',
          950: 'var(--xedu-emerald-950)',
        },
        'xedu-sky': {
          50:  'var(--xedu-sky-50)',
          100: 'var(--xedu-sky-100)',
          200: 'var(--xedu-sky-200)',
          300: 'var(--xedu-sky-300)',
          400: 'var(--xedu-sky-400)',
          500: 'var(--xedu-sky-500)',
          600: 'var(--xedu-sky-600)',
          700: 'var(--xedu-sky-700)',
          800: 'var(--xedu-sky-800)',
          900: 'var(--xedu-sky-900)',
          950: 'var(--xedu-sky-950)',
        },
        'xedu-violet': {
          50:  'var(--xedu-violet-50)',
          100: 'var(--xedu-violet-100)',
          200: 'var(--xedu-violet-200)',
          300: 'var(--xedu-violet-300)',
          400: 'var(--xedu-violet-400)',
          500: 'var(--xedu-violet-500)',
          600: 'var(--xedu-violet-600)',
          700: 'var(--xedu-violet-700)',
          800: 'var(--xedu-violet-800)',
          900: 'var(--xedu-violet-900)',
          950: 'var(--xedu-violet-950)',
        },
        'xedu-gold': {
          50:  'var(--xedu-gold-50)',
          100: 'var(--xedu-gold-100)',
          200: 'var(--xedu-gold-200)',
          300: 'var(--xedu-gold-300)',
          400: 'var(--xedu-gold-400)',
          500: 'var(--xedu-gold-500)',
          600: 'var(--xedu-gold-600)',
          700: 'var(--xedu-gold-700)',
          800: 'var(--xedu-gold-800)',
          900: 'var(--xedu-gold-900)',
          950: 'var(--xedu-gold-950)',
        },
        'xedu-bg': {
          DEFAULT:  'var(--xedu-bg)',
          canvas:   'var(--xedu-bg-canvas)',
          rail:     'var(--xedu-bg-rail)',
          panel:    'var(--xedu-bg-panel)',
          elevated: 'var(--xedu-bg-elevated)',
          subtle:   'var(--xedu-bg-subtle)',
          floating: 'var(--xedu-bg-floating)',
        },
        'xedu-border': {
          DEFAULT: 'var(--xedu-border)',
          strong:  'var(--xedu-border-strong)',
          hover:   'var(--xedu-border-hover)',
        },
        'xedu-text': {
          DEFAULT: 'var(--xedu-text)',
        },
      },

      /* ── Border radius (4px step system) ── */
      borderRadius: {
        xs:   '6px',
        sm:   '8px',
        md:   '10px',
        lg:   '12px',
        xl:   '14px',
        '2xl':'16px',
        '3xl':'20px',
        '4xl':'24px',
      },

      /* ── Elevation shadows ── */
      boxShadow: {
        xs:       'var(--xedu-shadow-xs)',
        sm:       'var(--xedu-shadow-sm)',
        md:       'var(--xedu-shadow-md)',
        lg:       'var(--xedu-shadow-lg)',
        xl:       'var(--xedu-shadow-xl)',
        card:     'var(--shadow-card)',
        elevated: 'var(--xedu-shadow-lg)',
        dialog:   'var(--xedu-shadow-dialog)',
        floating: 'var(--xedu-shadow-floating)',
        pill:     'var(--xedu-shadow-pill)',
        'glow-primary': 'var(--xedu-shadow-glow-primary)',
        'glow-amber':   'var(--xedu-shadow-glow-amber)',
        'glow-ruby':    'var(--xedu-shadow-glow-ruby)',
        'glow-sky':     'var(--xedu-shadow-glow-sky)',
        'glow-violet':  'var(--xedu-shadow-glow-violet)',
      },

      /* ── Spacing (4px base grid) ── */
      spacing: {
        '0.5': '2px',
        '1':   '4px',
        '1.5': '6px',
        '2':   '8px',
        '2.5': '10px',
        '3':   '12px',
        '3.5': '14px',
        '4':   '16px',
        '5':   '20px',
        '6':   '24px',
        '7':   '28px',
        '8':   '32px',
        '9':   '36px',
        '10':  '40px',
        '11':  '44px',
        '12':  '48px',
        'header': 'var(--header-height, 64px)',
        'sidebar': 'var(--sidebar-width, 272px)',
        'sidebar-collapsed': 'var(--sidebar-collapsed, 84px)',
      },

      /* ── Animations ── */
      keyframes: {
        'fade-in': {
          from: { opacity: '0' },
          to:   { opacity: '1' },
        },
        'fade-up': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-in-left': {
          from: { opacity: '0', transform: 'translateX(-8px)' },
          to:   { opacity: '1', transform: 'translateX(0)' },
        },
        'count-up': {
          from: { opacity: '0', transform: 'translateY(4px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        'accordion-down': {
          from: { height: '0' },
          to:   { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to:   { height: '0' },
        },
      },
      animation: {
        'fade-in':       'fade-in 150ms ease-out',
        'fade-up':       'fade-up 150ms ease-out',
        'slide-in-left': 'slide-in-left 150ms ease-out',
        'count-up':      'count-up 150ms ease-out',
        'accordion-down':'accordion-down 150ms ease-out',
        'accordion-up':  'accordion-up 150ms ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};

export default config;
